version: "3.8"

services:
  db:
    image: postgres:16.0
    container_name: postgresql
    environment:
      POSTGRES_DB: lqp_db
      POSTGRES_USER: DBuser
      POSTGRES_PASSWORD: DBpass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres_data:
