apps:
  namespace: dev
  image: ghcr.io/phurits/oqp-backend
  tag: dev
  replicas: 1
  imagePullSecrets: ghcr-registry
  port: 8080
ingress:
  host: backend.dev.livequizplatform.online
  path: /
  serviceType: ClusterIP
  tlsSecretName: tls-backend-dev
extraEnv:
  ALLOW_ORIGINS: 'https://inquesto.dev.livequizplatform.online,https://live.inquesto.dev.livequizplatform.online,http://localhost:3000,http://localhost:5173'
  HOST: postgresql.default.svc.cluster.local
  PORT: "8080"
  DB_HOST: postgresql.default.svc.cluster.local
  DB_PORT: "5432"
  DB_USER: DBuser
  DB_PASSWORD: DBpass
  DB_NAME: test_lqp_db
  CACHE_HOST: redis-master.default.svc.cluster.local
  CACHE_PORT: "6379"
  CACHE_PASS: P@ssw0rd@Redis
  ACCESS_TOKEN_SECRET: tGh3VrNtGh3VrNtGh3VrNtGh3VrNtGh3VrNtGh3VrNtGh3VrNtGh3VrNV3FrxNtGhyV3Fr
  REFRESH_TOKEN_SECRET: Wz9pQsfK1JWz9pQsfK1JWz9pQsfK1JWz9pQsfK1JWz9pQsfK1JWz9pQsfK1JWz9pQsfK1J